### ISSUE TITLE
TypeError: Incorrect padding on base64decode of ciphertext[:3] for legacy encoded values

### ISSUE THREAD

**Issue by ghost** [HurricaneLabs/splunksecrets#5]
https://github.com/HurricaneLabs/splunksecrets/blob/f104e60dade59b7071f503846bf8126f34c78b8e/splunksecrets.py#L22

Example of error:

```
Traceback (most recent call last):
  File "/home/rfrey2/python/virtualenv/environments/splunksecrets/bin/splunksecrets", line 10, in <module>
    sys.exit(main())
  File "/home/rfrey2/python/virtualenv/environments/splunksecrets/local/lib/python2.7/site-packages/splunksecrets.py", line 146, in main
    output = decrypt(key, ciphertext, args.nosalt)
  File "/home/rfrey2/python/virtualenv/environments/splunksecrets/local/lib/python2.7/site-packages/splunksecrets.py", line 24, in decrypt
    ciphertext = base64.b64decode(ciphertext[3:])
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```

Something like this seems to fix the issue (may not be perfect but it works):

```
def decrypt(secret, ciphertext, nosalt=False):
    """Given the first 16 bytes of splunk.secret, decrypt a Splunk password"""
    plaintext = None
    if ciphertext.startswith("$1$"):

        try:
                ciphertext = base64.b64decode(ciphertext[3:])
        except TypeError:
                try:
                        ciphertext = base64.b64decode(ciphertext[3:] + "===")
                except Exception as e:
                        print(e)
                        exit(1)

        key = secret[:16]
```

**Comment by mcm** [comment]
Interesting. I've never seen this happen before. I don't suppose you have a ciphertext you could share where this happens? I've never seen Splunk incorrectly pad the password before.

**Comment by mcm** [comment]
This looks like it might've been a copy/paste issue. Let me know if that's not the case though and I'll be happy to take a look. It might be worth doing even if it's just a copy/paste error.

**Comment by ghost** [comment]
I went back and checked my work and did notice an error in what I was passing in via the --password argument. Regardless, I ultimately added this to my copy of the script to try and handle issues like this in the future.

```
def decrypt(secret, ciphertext, nosalt=False):
    """Given the first 16 bytes of splunk.secret, decrypt a Splunk password"""
    plaintext = None
    if ciphertext.startswith("$1$"):

    	try:
    		ciphertext = base64.b64decode(ciphertext[3:])
    	except TypeError:
    		if len(ciphertext[3:]) % 4:
                padded_ciphertext += '=' * (4 - len(value) % 4)
                ciphertext = base64.b64decode(padded_ciphertext)
```

**Comment by mcm** [comment]
Thanks. It's definitely worth handling for convenience, so I've release 0.4.2 with something similar included. I did it slightly differently so it's covered in both old-style and new-style decryption.
